### ISSUE TITLE
New storagePath directory causing issues

### ISSUE THREAD

**Issue by ColdSteamyShower** [tarekel96/Electron_BackgroundImage_App#16]
[1] {"access_token":"IGQVJXMDhsOWxMbEtkUVhsQnhPdlRCZA2xKRjkzTnVuaVJuQlFVbnY4amp5aXFxT2FrWV9BUzVwbnl5YjktYWxjaDg2RXVNTHdyand4ZAkF1MW04ZAXhLLWVxR0x0TnpBSUVnRE8tMGFyWFhDTkpxUkw2eEdzQlFMMlFUalhj","user_id":17841447467087620}

[1] (node:19096) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'S:\Documents\desktop items\CPSC Courses\Chapman\software engineering\screensaver\dual-modes\screensaver-display/local_settings/IGBasicDisplayLongLivedToken'

[1]     at Object.openSync (fs.js:476:3)

[1]     at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)

[1]     at Object.writeFileSync (fs.js:1467:35)

[1]     at fetchTokens (S:\Documents\desktop items\CPSC Courses\Chapman\software engineering\screensaver\dual-modes\screensaver-display\api-components\redirectAuthenticate.js:110:7)

[1]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

[1] (Use `electron --trace-warnings ...` to show where the warning was created)

[1] (node:19096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 

To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

[1] (node:19096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[0] Terminate batch job (Y/N)?

PS S:\Documents\desktop items\CPSC Courses\Chapman\software engineering\screensaver\dual-modes\screensaver-display> S:\Documents\desktop items\CPSC Courses\Chapman\software engineering\screensaver\dual-modes\screensaver-display\node_modules\electron\dist\electron.exe exited with signal SIGINT

[1] Terminate batch job (Y/N)? wait-on http://localhost:3000 && electron . --settings exited with code 1

[0] cross-env BROWSER=none npm run react-start exited with code 1

**Comment by Superchig** [comment]
Just for the record, we've decided to stick with using app.getPath('appData') for storagePath.
